# Generated by Django 2.1.7 on 2019-02-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event', models.IntegerField(choices=[(0, 'Normal'), (1, 'Misplaced Luggage'), (3, 'Violent Confrontation'), (3, 'Threatening Object')], default=0)),
                ('size', models.IntegerField()),
                ('upload', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
